kafka:
  bootstrap-servers: localhost:9092
  schema-registry-url: http://localhost:8081
  
kafka-streams:  
  applicationId: test
  verbose: true
  expired-check: true

  topic:
    source: person-before
    sink: person-after

spring:
  application:
    name: test
  main:
    allow-bean-definition-overriding: true    
    
debug: false

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    encoding: "@project.build.sourceEncoding@"
    java.version: "@java.version@"

management:
  server:port: 8080
  endpoint:
    enabled-by-default: true
    health:
      show-details: always
    metrics:enabled: true
  endpoints:
    web:
      exposure:
        include: "*"